exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: PORTABLE LINUX APPS
description: The database of all AppImage packages and portable applications for GNU/Linux.
