exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer
markdown: GFM
github:
  private: false
  repository_url: "https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io"
  
title: PORTABLE LINUX APPS
description: The database of all AppImage packages and portable applications for GNU/Linux.
site_favicon: favicon.ico
