title: PORTABLE LINUX APPS
collections:
  categories:
    output: true
description:  >- # this means to ignore newlines until "baseurl:"
  The first AUR-inspired Software Center of all AppImage packages and portable
  applications for GNU/Linux.
baseurl: ""
url: https://portable-linux-apps.github.io/
repository: Portable-Linux-Apps/portable-linux-apps.github.io
avatar: favicon.ico

google_analytics:
piwik_analytics:

exclude:
  - node_modules
  - script
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .github/
  - .gitignore
  - .git/

sass:
  style: :compressed

theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: GFM
github:
  private: false
  repository_url: "https://github.com/Portable-Linux-Apps/Portable-Linux-Apps.github.io"
